export enum MsgType {
    MSG_SEND = "MSG_SEND",
    ERROR = "ERROR",
    MSG_FROM_USER = "MSG_FROM_USER",
    MSG_COUNT_NOT_READED_FROM_USER = "MSG_COUNT_NOT_READED_FROM_USER",
    MSG_DELETE = "MSG_DELETE",
    MSG_EDIT = "MSG_EDIT",
}
