export enum UserType {
  USER_LOGIN = "USER_LOGIN",
  ERROR = "ERROR",
  USER_LOGOUT = "USER_LOGOUT",
  USER_EXTERNAL_LOGIN = "USER_EXTERNAL_LOGIN",
  USER_EXTERNAL_LOGOUT = "USER_EXTERNAL_LOGOUT",
  LOGGED_USER = "loggedUser",
}
